### PR TITLE
updated CEC with new classes

### PR DESCRIPTION
**Pull request by tgelmi-candusso**
updated classes, deleted resistance values

### CODE REVIEW

**Comment by georod** [comment]
Hi. I think we are missing commas between the values in the CSV files? If so, can you please add them. Thanks

**Comment by tgelmi-candusso** [comment]
I’ll add them directly on the github

Tiziana A. Gelmi Candusso

On Apr 12, 2023, at 23:35, Peter R. ***@***.***> wrote:

﻿

Hi. I think we are missing commas between the values in the CSV files? If so, can you please add them. Thanks

**Comment by tgelmi-candusso** [comment]
description,rgb,value,mcsc_class,resistance_lm,resistance_sm,mcsc_value
 Temperate or sub-polar needleleaf forest, RGB 0 61 0,1,dense_green_area,5,5,9
 Sub-polar taiga needleleaf forest, RGB 148 156 112,2,dense_green_area,5,5,9
 Tropical or sub-tropical broadleaf evergreen forest, RGB 0 99 0,3,dense_green_area,5,5,9
 Tropical or sub-tropical broadleaf deciduous forest, RGB 30 171 5,4,dense_green_area,5,5,9
 Temperate or sub-polar broadleaf deciduous forest, RGB 20 140 61,5,dense_green_area,5,5,9
 Mixed forest, RGB 92 117 43,6,dense_green_area,5,5,9
 Tropical or sub-tropical shrubland, RGB 179 158 43,7,hetero_green_area,10,10,8
 Temperate or sub-polar shrubland, RGB 179 138 51,8,hetero_green_area,10,10,8
 Tropical or sub-tropical grassland, RGB 232 220 94,9,open_green_area,15,15,6
 Temperate or sub-polar grassland, RGB 225 207 138,10,open_green_area,15,15,6
 Sub-polar or polar shrubland-lichen-moss, RGB 156 117 84,11,open_green_area,15,15,6
 Sub-polar or polar grassland-lichen-moss, RGB 186 212 143,12,open_green_area,15,15,6
 Sub-polar or polar barren-lichen-moss, RGB 64 138 112,13,open_green_area,15,15,6
 Wetland, RGB 107 163 138,14,hetero_green_area,10,10,8
 Cropland, RGB 230 174 102,15,resourceful_green_area,10,10,7
 Barren lands, RGB 168 171 174,16,open_green_area,15,15,6
 Urban, RGB 220 33 38,17,residential,40,30,4
 Water, RGB 76 112 163,18,water,100,100,10
 Snow and Ice, RGB 255 250 255,19,water,100,100,10

**Review by tgelmi-candusso — COMMENTED** [review]
description,rgb,value,mcsc_class,resistance_lm,resistance_sm,mcsc_value
 Temperate or sub-polar needleleaf forest, RGB 0 61 0,1,dense_green_area,5,5,9
 Sub-polar taiga needleleaf forest, RGB 148 156 112,2,dense_green_area,5,5,9
 Tropical or sub-tropical broadleaf evergreen forest, RGB 0 99 0,3,dense_green_area,5,5,9
 Tropical or sub-tropical broadleaf deciduous forest, RGB 30 171 5,4,dense_green_area,5,5,9
 Temperate or sub-polar broadleaf deciduous forest, RGB 20 140 61,5,dense_green_area,5,5,9
 Mixed forest, RGB 92 117 43,6,dense_green_area,5,5,9
 Tropical or sub-tropical shrubland, RGB 179 158 43,7,hetero_green_area,10,10,8
 Temperate or sub-polar shrubland, RGB 179 138 51,8,hetero_green_area,10,10,8
 Tropical or sub-tropical grassland, RGB 232 220 94,9,open_green_area,15,15,6
 Temperate or sub-polar grassland, RGB 225 207 138,10,open_green_area,15,15,6
 Sub-polar or polar shrubland-lichen-moss, RGB 156 117 84,11,open_green_area,15,15,6
 Sub-polar or polar grassland-lichen-moss, RGB 186 212 143,12,open_green_area,15,15,6
 Sub-polar or polar barren-lichen-moss, RGB 64 138 112,13,open_green_area,15,15,6
 Wetland, RGB 107 163 138,14,hetero_green_area,10,10,8
 Cropland, RGB 230 174 102,15,resourceful_green_area,10,10,7
 Barren lands, RGB 168 171 174,16,open_green_area,15,15,6
 Urban, RGB 220 33 38,17,residential,40,30,4
 Water, RGB 76 112 163,18,water,100,100,10
 Snow and Ice, RGB 255 250 255,19,water,100,100,10

**Pull request closed without merging**
